apiVersion: v1
kind: Service
metadata:
  name: cms-svc
spec:
  type: ClusterIP
  selector:
    app: cms
  ports:
    - name: nodejs
      port: 3002
      targetPort: nodejs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cms
  labels:
    app: endpoint
data:
  config.js: |-
    module.exports = {
        endpoint : {
            mongodb: "mongodb://mongo-svc/berries",
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-v1
  labels:
    app: cms
    version: v1
spec:
  selector:
    matchLabels:
      app: cms
      version: v1
  replicas: 1
  template:
    metadata:
      name: cms
      labels:
        app: cms
        version: v1
    spec:
      containers:
        - name: cms-v1
          image: g3.skb:8500/btv/cms-v1:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: app-config
            mountPath: /app/config.js
            subPath: "config.js"
          ports:
          - name: nodejs
            containerPort: 3002
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /
              port: nodejs
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: nodejs
            initialDelaySeconds: 1
            periodSeconds: 3
      volumes:
      - name: app-config
        configMap:
          name: cms
          items:
          - key: config.js
            path: config.js
            